task: cartpole
num_episodes: 100
gym_env_name: CartPole-v1
render_mode: None
continuous: True
num_position_bins: 0
num_theta_bins: 0
logdir: logs/cartpole_v3
actions: 2
states: 4
max_traj_count: 20
max_traj_length: 300
template_dir: agent/policy/templates
llm_si_template_name: cont_cartpole_si.j2
llm_ui_template_name: None
llm_output_conversion_template_name: cont_cartpole_llm_output_conversion.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: True
reset_llm_conversation: True
