task: grid_world
experiments: 5
num_episodes: 20
gym_env_name: FrozenLake-v1
render_mode: None
logdir: logs/openai/frozen_lake/4x4
actions: [["left", "down", "right", "up"]]
grid_size: 4
max_traj_count: 20
max_traj_length: 100
template_dir: agent/policy/templates
llm_si_template_name: frozenlake_si.j2
#llm_ui_template_name: hopper_episode_buffer.j2
llm_output_conversion_template_name: frozenlake_llm_output_conversion.j2
#llm_model_name: gpt-4o
#llm_model_name: gemini-2.0-flash-exp
llm_model_name: o3-mini-2025-01-31
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: True
reset_llm_conversation: False
