task: blackjack
num_episodes: 100
gym_env_name: Blackjack-v1
render_mode: null
logdir: logs/blackjack_v1_take_1
actions: [ [ 0, 1 ] ]
states: [ [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32 ], [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ], [ 0, 1 ] ]
max_traj_count: 100
max_traj_length: 50
template_dir: agent/policy/templates
llm_si_template_name: blackjack_si.j2
llm_output_conversion_template_name: blackjack_llm_output_conversion.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
