task: cartpole
experiments: 10
num_episodes: 400
gym_env_name: Cartpole-v1
render_mode: None
logdir: /scratch/melmisti/logs/evaluation/cartpole/numeric_hf_oss_20B_baseline_400ep
actions: 2
states: 4
max_traj_count: 20
max_traj_length: 100
warmup_episodes: 20
template_dir: agent/policy/templates
llm_si_template_name: numeric_optimization.j2
llm_ui_template_name: non_standard/mountaincar_cont_episode.j2
llm_output_conversion_template_name: output_conversion.j2
env_desc_file: None
#llm_model_name: gpt-Oss
llm_model_name: openai/gpt-oss-20b
model_type: HF
base_model: openai/gpt-oss-20b
num_evaluation_episodes: 20
step_size: 1.0
reset_llm_conversation: False
print_episode: 20
max_limit: 100
title: Cartpole as ProPS with OSS 20B Baseline
