task: cartpole
experiments: 10
num_episodes: 20
gym_env_name: CartPole-v1
render_mode: None
continuous: True
num_position_bins: 0
num_theta_bins: 0
logdir: logs/gemini/cartpole_as_optimization
actions: 2
states: 4
max_traj_count: 20
max_traj_length: 300
template_dir: agent/policy/templates
llm_si_template_name: cont_optimize_si.j2
llm_ui_template_name: cont_optimize_ui.j2
llm_output_conversion_template_name: cont_cartpole_llm_output_conversion.j2
llm_model_name: gemini-2.0-flash-exp
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: False
reset_llm_conversation: False
