task: hopper
experiments: 10
num_episodes: 100
gym_env_name: Hopper-v5
render_mode: None
logdir: logs/gemini/hopper/no_context
actions: 3
states: 11
max_traj_count: 20
max_traj_length: 300
template_dir: agent/policy/templates
llm_si_template_name: hopper_context_si.j2
llm_ui_template_name: hopper_episode.j2
llm_output_conversion_template_name: cont_cartpole_llm_output_conversion.j2
#llm_model_name: gpt-4o
llm_model_name: gemini-2.0-flash-exp
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: True
reset_llm_conversation: False
