task: cont_space_llm_num_optim
num_episodes: 400
experiments: 10
gym_env_name: Hopper-v5
render_mode: None
logdir: /scratch/sgrover6/logs/evaluation/baseline/hopper/numeric_hf_oss_20B_baseline_400ep
actions: 3
states: 11
max_traj_count: 20
max_traj_length: 100
warmup_episodes: 20
template_dir: agent/policy/templates
llm_si_template_name: numeric_optimization.j2
llm_ui_template_name: non_standard/hopper_episode.j2
llm_output_conversion_template_name: hopper_llm_output_conversion.j2
env_desc_file: None
#llm_model_name: gpt-oss
llm_model_name: openai/gpt-oss-20b
model_type: HF
base_model: openai/gpt-oss-20b
num_evaluation_episodes: 20
step_size: 0.1
reset_llm_conversation: False
print_episode: 20
max_limit: 100
title: Swimmer as ProPS s ProPS HF OSS 20B Baseline
