task: inverted_pendulum
experiments: 30
num_episodes: 100
gym_env_name: InvertedPendulum-v5
render_mode: None
logdir: logs/evaluation/inv_pend/numeric_qwen2.5_14B_epoch5
actions: 1
states: 4
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numeric_optimization.j2
llm_ui_template_name: non_standard/mountaincar_cont_episode.j2
llm_output_conversion_template_name: output_conversion.j2
env_desc_file: None
#llm_model_name: gpt-4o
llm_model_name: logs/finetune/completed/qwen2.5_14B_numeric_cont_mc/final
model_type: OFFLINE
base_model: Qwen/Qwen2.5-14B-Instruct
num_evaluation_episodes: 20
step_size: 0.5
reset_llm_conversation: False
print_episode: 20
max_limit: 1000
title: Inverted Pendulum as ProPS with Qwen2.5 14B 5th Epoch
