task: llm_num_optim_q_table
world: mountaincar
num_episodes: 400
gym_env_name: MountainCar-v0
render_mode: null
logdir: logs/mountaincar_llm_num_optim_q_table_400_rank_10_take_1
actions: [ [ 0, 1, 2 ] ]
states: [ [ -5, -4, -3, -2, -1, 0, 1, 2, 3, 4 ], [ -5, -4, -3, -2, -1, 0, 1, 2, 3, 4 ] ]
max_traj_count: 1000
max_traj_length: 50
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_adaptive_hopper_no_bias_range_expected_r_rndm_proj_rank_all_search_step.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
num_training_rollouts: 20
warmup_episodes: 20
warmup_dir: null
optimum: -110.0
rank: 10
search_std: 0.1
