task: maze_5x5
num_episodes: 100
gym_env_name: maze-sample-5x5-v0
render_mode: false
logdir: logs/maze5x5_o3_mini_new_template_7_take_3
actions: [ [ 0, 1, 2, 3 ] ]
states: [ [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24 ] ]
max_traj_count: 20
max_traj_length: 50
template_dir: agent/policy/templates
llm_si_template_name: maze5x5_si_4o_7.j2
llm_output_conversion_template_name: maze3x3_llm_output_conversion.j2
llm_model_name: o3-mini-2025-01-31
num_evaluation_episodes: 1
