task: mc_continuous
experiments: 2
num_episodes: 100
gym_env_name: MountainCarContinuous-v0
render_mode: None
logdir: logs/finetune/evaluation/continuous_mc/qwen2.5_0.5B_finetuned_epoch5
actions: 1
states: 2
max_traj_count: 20
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: mountaincar_cont_domain.j2
llm_ui_template_name: mountaincar_cont_episode.j2
llm_output_conversion_template_name: mountaincar_cont_llm_output_conversion.j2
#llm_model_name: gpt-4o
llm_model_name: logs/finetune/qwen_2.5_5_epoch/mountain_car_continuous-test
model_type: OFFLINE
base_model: Qwen/Qwen2.5-0.5B-Instruct
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: False
reset_llm_conversation: False
print_episode: 50
max_limit: 100
