task: mc_continuous
experiments: 10
num_episodes: 100
gym_env_name: MountainCarContinuous-v0
render_mode: None
logdir: <logging directory, which stores execution, responses and final results>
actions: 1
states: 2
max_traj_count: 20
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numeric_optimization_3_params.j2
llm_ui_template_name: non_standard/mountaincar_cont_episode.j2
llm_output_conversion_template_name: output_conversion_3_params.j2
env_desc_file: None
#llm_model_name: gpt-4o
llm_model_name: <location to the final folder>
model_type: OFFLINE
base_model: Qwen/Qwen2.5-14B-Instruct
num_evaluation_episodes: 20
step_size: 1.0
reset_llm_conversation: False
print_episode: 20
max_limit: 100
title: Mountain Car Continuous as ProPS Qwen2.5 14B 5th Epoch
