task: mc_continuous
experiments: 2
num_episodes: 100
gym_env_name: MountainCarContinuous-v0
render_mode: None
logdir: logs/evaluation/continuous_mc/qwen2.5_3B_baseline
actions: 1
states: 2
max_traj_count: 20
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: mountaincar_cont_domain.j2
llm_ui_template_name: mountaincar_cont_episode.j2
llm_output_conversion_template_name: mountaincar_cont_llm_output_conversion.j2
#llm_model_name: gpt-4o
llm_model_name: Qwen/Qwen2.5-3B-Instruct
model_type: HF
base_model: Qwen/Qwen2.5-3B-Instruct
num_evaluation_episodes: 20
record_video: True
use_replay_buffer: False
reset_llm_conversation: False
print_episode: 20
max_limit: 100
