task: mountaincar_continuous
num_episodes: 100
gym_env_name: MountainCar-v0
render_mode: null
logdir: logs/mountaincar_continuous_v1_100
dim_actions: 3
dim_states: 2
max_traj_count: 20
max_traj_length: 300
template_dir: agent/policy/templates
llm_si_template_name: mountaincar_continuous_si.j2
llm_output_conversion_template_name: mountaincar_continuous_llm_output_conversion.j2
llm_model_name: o1-preview
num_evaluation_episodes: 20
