task: mountaincar_continuous_action_llm_num_optim
num_episodes: 100
gym_env_name: MountainCarContinuous-v0
render_mode: null
logdir: logs/mountaincar_continuous_action_llm_num_optim_400_std_1_expected_r_norm_take_4_3
dim_actions: 1
dim_states: 2
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_mountaincar_expected_r_no_range.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: warmup_episodes/mountaincar_norm
search_std: 1
norm: true
