task: mujoco_hopper_llm_num_optim_no_bias_iterative
num_episodes: 300
gym_env_name: Hopper-v5
render_mode: null
logdir: logs/mujoco_hopper_llm_num_optim_300_improved_std_range_no_bias_iterative_take_2
dim_actions: 3
dim_states: 11
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: mujoco_hopper_num_optim_iter_si.j2
llm_1st_round_template_name: mujoco_hopper_num_optim_iter_round_1.j2
llm_round_template_name: mujoco_hopper_num_optim_iter_reduced_process.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
