task: mujoco_hopper_llm_num_optim_no_bias
num_episodes: 400
gym_env_name: Hopper-v5
render_mode: null
logdir: logs/mujoco_hopper_llm_num_optim_400_no_bias_range_std_small_expected_r_elite_take_1
dim_actions: 3
dim_states: 11
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_small_hopper_no_bias_range_expected_r_elite.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
norm: false
