task: mujoco_hopper_llm_num_optim_no_bias
num_episodes: 250
gym_env_name: Hopper-v5
render_mode: null
logdir: logs/mujoco_hopper_llm_num_optim_400_no_bias_range_std_2_expected_r_beam_temp_1.2_gpt-4o-mini_3_forward_reward_take_2
dim_actions: 3
dim_states: 11
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_change_hopper_no_bias_range_expected_r_beam.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o-mini
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
beam: true
beam_width: 10
num_new_candidate: 5
temperature: 1.2
