task: mujoco_llm_num_optim_no_bias_rndm_proj
num_episodes: 400
gym_env_name: LunarLander-v3
render_mode: null
logdir: logs/lunalander_llm_num_optim_400_with_bias_rndm_proj_full_rank_take_5
dim_actions: 4
dim_states: 8
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_adaptive_hopper_no_bias_range_expected_r_rndm_proj_rank_all_search_step.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
rank: 36
bias: true
optimum: 300
