task: mujoco_invertedpendulum_llm_num_optim_no_bias
num_episodes: 1000
gym_env_name: InvertedPendulum-v5
render_mode: null
logdir: logs/mujoco_invertedpendulum_llm_num_optim_300_no_bias_range_std_2
dim_actions: 1
dim_states: 4
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_2_invertedpendulum_no_bias_range.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
