task: nim
num_episodes: 300
gym_env_name: Nim-v0
render_mode: null
logdir: logs/nim_4o_reflex_10_training_rollouts
actions: [ [ 0, 1, 2 ] ]
states: [ [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] ]
max_traj_count: 1000
template_dir: agent/policy/templates
llm_si_template_name: nim_si_4o_reflex.j2
llm_output_conversion_template_name: nim_llm_output_conversion.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
num_training_rollouts: 10
