task: panda_reach_llm_num_optim_no_bias
num_episodes: 300
gym_env_name: PandaReachDense-v3
render_mode: rgb_array
logdir: logs/panda_reach_llm_num_optim_300_no_bias_std_1_range
dim_actions: 3
dim_states: 9
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numerical_optimization_search_std_1_panda_reach_no_bias_range_expected_r.j2
llm_output_conversion_template_name: swimmer_continuous_sas_llm_output_conversion_v4.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
search_std: -1
