task: pendulum
num_episodes: 20
gym_env_name: Pendulum-v1
render_mode: null
num_costheta_bins: 5
num_sintheta_bins: 5
num_angular_velocity_bins: 5
num_action_bins: 5
logdir: logs/pendulum_v3
actions: [ [ 0, 1, 2, 3, 4 ] ]
states: [ [ -2, -1, 0, 1, 2 ], [ -2, -1, 0, 1, 2 ], [ -2, -1, 0, 1, 2 ] ]
max_traj_count: 20
max_traj_length: 200
template_dir: agent/policy/templates
llm_si_template_name: pendulum_si_3.j2
llm_output_conversion_template_name: pendulum_llm_output_conversion_3.j2
llm_model_name: o1-preview
num_evaluation_episodes: 20
