task: swimmer_continuous_mean_std_sas
num_episodes: 30
gym_env_name: Swimmer-v5
render_mode: null
logdir: logs/swimmer_continuous_mean_std_sas_v2_30
dim_actions: 2
dim_states: 8
max_traj_count: 60
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: mountaincar_continuous_sas_si.j2
llm_output_conversion_template_name: mountaincar_continuous_sas_llm_output_conversion.j2
llm_model_name: o1-preview
num_evaluation_episodes: 20
warmup_episodes: 20
