task: swimmer
experiments: 10
num_episodes: 400
gym_env_name: Swimmer-v5
render_mode: None
logdir: logs/evaluation/swimmer/numeric_qwen2.5_14B_baseline
actions: 2
states: 8
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: numeric_optimization.j2
llm_ui_template_name: non_standard/mountaincar_cont_episode.j2
llm_output_conversion_template_name: output_conversion.j2
env_desc_file: None
#llm_model_name: gpt-4o
llm_model_name: Qwen/Qwen2.5-14B-Instruct
model_type: HF
base_model: Qwen/Qwen2.5-14B-Instruct
num_evaluation_episodes: 20
step_size: 0.1
reset_llm_conversation: False
print_episode: 20
max_limit: 250
title: Swimmer as ProPS Qwen2.5 14B Baseline
