task: swimmer_continuous_random_search
num_episodes: 400
gym_env_name: Swimmer-v5
render_mode: null
logdir: logs/swimmer_continuous_random_search_0.01
dim_actions: 2
dim_states: 8
max_traj_count: 1000
max_traj_length: 1000
num_evaluation_episodes: 20
warmup_episodes: 20
search_std: 0.01
warmup_dir: warmup_episodes/swimmer
