task: swimmer_continuous
num_episodes: 100
gym_env_name: Swimmer-v5
render_mode: null
logdir: logs/swimmer_continuous_v1_100
dim_actions: 2
dim_states: 8
max_traj_count: 20
max_traj_length: 300
template_dir: agent/policy/templates
llm_si_template_name: swimmer_continuous_si.j2
llm_output_conversion_template_name: swimmer_continuous_llm_output_conversion.j2
llm_model_name: o1-preview
num_evaluation_episodes: 20
