from abc import ABC, abstractmethod

class BaseAgent(ABC):
    @abstractmethod
    def initialize_policy(self, states, actions): ...
    @abstractmethod
    def add_warmup(self, world, logdir): ...
    @abstractmethod
    def train_policy(self, world, logdir): ...
    @abstractmethod
    def evaluate_policy(self, world, logdir): ...

